add cached-path file utils
guillaume-be/rust-bert pull request #74
Opened 2020-09-09 18:56 UTC by epwalsh

So far I've just added a `common/file_utils.rs` module. The idea being that this would replace what's currently in `common/resources.rs`.

My question for you is, do you want to keep the `LocalResource` and `RemoteResource` abstractions?

2020-09-10 16:02 UTC, guillaume-be commented
@epwalsh thank you for the suggestions. I believe the `cached_path` functionality could be easily added without causing breaking changes. My idea was to just replace the body of the existing https://github.com/guillaume-be/rust-bert/blob/a52279e24d879db2a4b79833ac409cecd6b3f2ff/src/common/resources.rs#L186 and replace the check for the existing file & download by a call to `cached_path`. Could you please use the existing file and methods in `resources` instead of creating a separate `file_utils` file?

For now I'd like to keep the concept of local and remote resources - and I believe this would still work with the proposed changes.

2020-09-10 16:05 UTC, guillaume-be requested changes

2020-09-10 16:05 UTC, guillaume-be commented on Cargo.toml
> +cached-path = "0.4.0-rc1"
could you please ensure a release is added as a dependency for the final version of this PR?

2020-09-10 16:05 UTC, guillaume-be commented on src/common/file_utils.rs
> +use crate::common::error::RustBertError;
Please use the existing `resources` file for these utilities

2020-09-10 16:05 UTC, guillaume-be commented on src/common/file_utils.rs
> +fn _get_cache_directory() -> PathBuf {
This already exists at https://github.com/guillaume-be/rust-bert/blob/a52279e24d879db2a4b79833ac409cecd6b3f2ff/src/common/resources.rs#L150

2020-09-10 16:05 UTC, guillaume-be commented on src/common/file_utils.rs
> +pub fn cached_path(resource: &str) -> Result<PathBuf, RustBertError> {
Could you please wrap the cached path functionality directly in https://github.com/guillaume-be/rust-bert/blob/a52279e24d879db2a4b79833ac409cecd6b3f2ff/src/common/resources.rs#L186 ?

2020-09-10 16:31 UTC, epwalsh commented
Hey @guillaume-be, no problem.

One issue though is that, like `transformers/file_utils.py`, `cached-path` automatically generates a name for the files it downloads. The name is generated from a hash of the resource string and the ETag. But your `RemoteResource` struct takes a `target_path`.

I think I could make `cached-path` work with custom target paths but I'll have to change some things.

2020-09-10 18:45 UTC, guillaume-be commented
What if the target_path would point to a directory instead (i.e. remove the file name). 
```rust
impl BartModelResources {
    /// Shared under MIT license by the Facebook AI Research Fairseq team at https://github.com/pytorch/fairseq. Modified with conversion to C-array format.
    pub const BART: (&'static str, &'static str) = (
        "bart/model.ot",
        "https://cdn.huggingface.co/facebook/bart-large/rust_model.ot",
    );
}
```
Would for example become:
```rust
impl BartModelResources {
    /// Shared under MIT license by the Facebook AI Research Fairseq team at https://github.com/pytorch/fairseq. Modified with conversion to C-array format.
    pub const BART: (&'static str, &'static str) = (
        "bart",
        "https://cdn.huggingface.co/facebook/bart-large/rust_model.ot",
    );
}
```
and the `.ot` file would be dynamically generated by `cached_path`?

2020-09-10 18:53 UTC, epwalsh commented
That seems reasonable

2020-09-10 22:05 UTC, epwalsh commented
Just made some updates. CI will probably fail. Let me know if you're happy with the API and then I'll fix the compile errors. IMHO though it doesn't make sense to have a `download_resource` function when we get the same functionality from `Resource.get_local_path()`.

Let me know.

2020-09-11 05:17 UTC, guillaume-be commented on src/common/resources.rs
> +    /// If the resource is a remote resource, it is downlaoded and cached. Then the path
typo

2020-09-11 05:20 UTC, guillaume-be commented
@epwalsh Thank you for the change. The `get_local_path` indeed is more idiomatic and is a nicer way to get to access local resources or download remote files. I wanted to avoid breaking changes - maybe the `download_function` could be kept in parallel to the now standard `get_local_path` method, but deprecated for a version cycle, i.e.
```
#[deprecated(
    since = "0.9.1",
    note = "Please use `Resource.get_locao_path()` instead"
)]
```

2020-09-11 13:18 UTC, guillaume-be commented
@epwalsh Note that I am unable to build the `cached-path` crate on my machine (Windows). The `file-lock` dependency seems to be incompatible with my setup. This may be because `gcc` is listed as a dependency for this crate while the MSVC is used as a standard toolchain for windows machine. I have added a Windows build to the CI, hopefully it catches the issue.

2020-09-11 15:47 UTC, epwalsh commented
I'll add a Windows build to `cached-path` as well as see if I can fix the issue.

2020-09-11 17:58 UTC, epwalsh commented
Okay, should build on Windows now 👌

2020-09-11 18:01 UTC, epwalsh commented
Still TODO:
- [ ] Update resources like https://github.com/guillaume-be/rust-bert/pull/74#issuecomment-690615106
- [ ] Remove use of `download_resource` from examples and docs

2020-09-11 18:04 UTC, guillaume-be commented
@epwalsh This looks great thanks. 

Actually regarding the first TODO - one could potentially leave it the way it is. As you can see in the CI, one nice effect is that the target file name becomes the name of the folder where the cached version will be stored. This is quite nice as the hashed version makes it difficult to differentiate a `config.json` from a `vocab.txt` otherwise. The current path makes it easy to know exactly what each cache file corresponds to.

What do you think?

2020-09-11 18:06 UTC, epwalsh commented
> @epwalsh This looks great thanks.
> 
> Actually regarding the first TODO - one could potentially leave it the way it is. As you can see in the CI, one nice effect is that the target file name becomes the name of the folder where the cached version will be stored. This is quite nice as the hashed version makes it difficult to differentiate a `config.json` from a `vocab.txt` otherwise. The current path makes it easy to know exactly what each cache file corresponds to.
> 
> What do you think?

I'm fine with that if you are 👍

2020-09-11 21:03 UTC, guillaume-be commented on src/common/resources.rs
> +    Ok(resource.get_local_path()?)
just nitpicking, but I believe you could return `resource.get_local_path()` directly as this is a `Result<PathBuf, RustBertError>`

2020-09-11 21:10 UTC, epwalsh commented
@guillaume-be I noticed there were bunch of warnings (unrelated to this PR) when I ran clippy:

```bash
cargo clippy --all-targets --all-features -- -D warnings
```

Would you want to add a clippy check to the CI steps? And maybe documentation tests as well?

And I'm not sure if travis CI supports caching, but I've been able to get a huge speed-up in CI by using caching in GitHub Actions.

2020-09-12 06:54 UTC, guillaume-be commented
@epwalsh thank you very much for the PR!

I did notice the clippy warnings, I am working on fixing them and they will be addressed in the next release. I will then add a clippy check to the CI. The documentation tests are already run and check as part of the CI.

Regarding caching, I had it enabled at the beginning for this project, but the time required to compress and decompress the large cache was actually longer than downloading the files again.

2020-09-12 11:47 UTC, merged

2020-09-12 17:31 UTC, epwalsh commented
Oh right. By “large files” are you talking about model weights / checkpoint files?

I just meant caching the cargo build artifacts. That can make a big difference especially for Clippy, which takes a while to run from scratch every time